services:
  blog:
    build:
      context: ./blog
      target: development
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./blog:/app
      - astro_node_modules:/app/node_modules
      
volumes:
  astro_node_modules:
