name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /home/mgr/services/blog-jokko

            git pull origin main  || { echo "Git pull failed"; exit 1; }

            docker-compose down -v || { echo "Failed to remove volumes"; exit 1; }
            
            docker compose -f compose.yaml -f compose.prod.yaml up --build -d || { echo "Docker compose failed starting"; exit 1; }

